---
- name: Restart cribl edge
  ansible.builtin.systemd:
    name: "{{ cribl_packs_edge_service }}"
    state: restarted
    daemon_reload: false
  when: "'cribl_edge' in group_names"

- name: Restart cribl stream
  ansible.builtin.systemd:
    name: "{{ cribl_packs_stream_service }}"
    state: restarted
    daemon_reload: false
  when: "'cribl_stream_group' in group_names"
