---
# service_deadman role handlers

- name: Reload systemd and restart deadman timer
  ansible.builtin.systemd:
    name: "{{ service_deadman_service_name }}.timer"
    state: restarted
    daemon_reload: true
  listen: Reload systemd and restart deadman timer
